version: '3'
services:
  website:
    container_name: web-corona
    image: httpd:2.4
    build:
      context: ./
    volumes:
      - /Development/PetProjects/Dockercorona/src:/var/www/html/
    ports:
      - 8000:80
